### ISSUE TITLE
Меню при любой ширине экрана должно быть прижато вправо

### ISSUE THREAD

**Issue by mihan007** [mihan007/buskit.ru#1]
- сейчас на широких мониторах (1920 пикселей) меню смещается ближе к центру, так быть не должно.
- надо расставить разумный отступ справа, пикселей 50.

**Comment by maxmirazh33** [comment]
@mihan007 а brand("Деловая кухня") как разместить?

**Comment by mihan007** [comment]
@maxmirazh33 он все также слева, к нему добавится левее него лого, скоро тикет приедет. можешь пока вообще его сделать так, чтобы он симметрично правому краю был.

Т.е. отступ до начала надписи "Деловая кухня" = отступу от окончания блока меню справа.
