### ISSUE TITLE
Порядок пунктов меню и блоков сайта

### ISSUE THREAD

**Issue by mihan007** [mihan007/buskit.ru#6]
1. Главная
2. О проекте
3. Деловое меню
4. Главный гость
5. Эксперты
6. Партнеры
7. Команда - сейчас дропдаун, сделать просто пунктом и сделать отдельный блок на сайте
8. Контакты

**Comment by maxmirazh33** [comment]
Раздела "Контакты" не будет?

**Comment by mihan007** [comment]
@maxmirazh33 действительно, надо. добавил.
