### ISSUE TITLE
Пункт "Деловое меню"

### ISSUE THREAD

**Issue by mihan007** [mihan007/buskit.ru#8]
В виде https://dl.dropboxusercontent.com/s/rhdd1araqhmcq4o/2015-04-02%20at%2016.49.png сделать на основе информации из слайда.

**Comment by maxmirazh33** [comment]
Какие иконки должны быть? Сейчас их всего 4 разных, а пунктов 6.

**Comment by mihan007** [comment]
Пусть пока повторяются. Сделай отдельный тикет на их изменение, а этот закрой.
